#!/bin/bash

kubectl apply -f kubernetes-ingress/deployments/common/ns-and-sa.yaml
kubectl apply -f kubernetes-ingress/deployments/rbac/rbac.yaml
kubectl apply -f kubernetes-ingress/deployments/rbac/ap-rbac.yaml
kubectl apply -f kubernetes-ingress/deployments/rbac/apdos-rbac.yaml
kubectl apply -f kubernetes-ingress/deployments/common/default-server-secret.yaml
kubectl apply -f kubernetes-ingress/deployments/common/nginx-config.yaml
kubectl apply -f kubernetes-ingress/deployments/common/ingress-class.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/k8s.nginx.org_virtualservers.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/k8s.nginx.org_virtualserverroutes.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/k8s.nginx.org_transportservers.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/k8s.nginx.org_policies.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/appprotect.f5.com_aplogconfs.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/appprotect.f5.com_appolicies.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/appprotect.f5.com_apusersigs.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/appprotectdos.f5.com_apdoslogconfs.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/appprotectdos.f5.com_apdospolicy.yaml
kubectl apply -f kubernetes-ingress/deployments/common/crds/appprotectdos.f5.com_dosprotectedresources.yaml
kubectl apply -f kubernetes-ingress/deployments/deployment/appprotect-dos-arb.yaml
kubectl apply -f kubernetes-ingress/deployments/service/appprotect-dos-arb-svc.yaml
