apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: waf-base-httpbin
spec:
  policy:
    name: waf-base-httpbin
    description: NGINX App Protect WAF API Security Policy for the HTTPBIN
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    open-api-files:
#    - link: https://raw.githubusercontent.com/zikrillah/K8s-resource/master/httpbin-app/swagger-httpbin.json
    - link: https://raw.githubusercontent.com/zikrillah/K8s-resource/master/httpbin-app/httpbin.yaml
    blocking-settings:
      violations:
      - block: true
        description: Disallowed file upload content detected in body
        name: VIOL_FILE_UPLOAD_IN_BODY
      - block: true
        description: Mandatory request body is missing
        name: VIOL_MANDATORY_REQUEST_BODY
      - block: true
        description: Illegal parameter location
        name: VIOL_PARAMETER_LOCATION
      - block: true
        description: Mandatory parameter is missing
        name: VIOL_MANDATORY_PARAMETER
      - block: true
        description: JSON data does not comply with JSON schema
        name: VIOL_JSON_SCHEMA
      - block: true
        description: Illegal parameter array value
        name: VIOL_PARAMETER_ARRAY_VALUE
      - block: true
        description: Illegal Base64 value
        name: VIOL_PARAMETER_VALUE_BASE64
      - block: true
        description: Disallowed file upload content detected
        name: VIOL_FILE_UPLOAD
      - block: true
        description: Illegal request content type
        name: VIOL_URL_CONTENT_TYPE
      - block: true
        description: Illegal static parameter value
        name: VIOL_PARAMETER_STATIC_VALUE
      - block: true
        description: Illegal parameter value length
        name: VIOL_PARAMETER_VALUE_LENGTH
      - block: true
        description: Illegal parameter data type
        name: VIOL_PARAMETER_DATA_TYPE
      - block: true
        description: Illegal parameter numeric value
        name: VIOL_PARAMETER_NUMERIC_VALUE
      - block: true
        description: Parameter value does not comply with regular expression
        name: VIOL_PARAMETER_VALUE_REGEXP
      - block: true
        description: Illegal URL
        name: VIOL_URL
      - block: true
        description: Illegal parameter
        name: VIOL_PARAMETER
      - block: true
        description: Illegal empty parameter value
        name: VIOL_PARAMETER_EMPTY_VALUE
      - block: true
        description: Illegal repeated parameter name
        name: VIOL_PARAMETER_REPEATED
    filetypes:
#    - link: https://raw.githubusercontent.com/zikrillah/K8s-resource/master/httpbin-app/filetypes.yaml
      - name: '*'
        type: wildcard
        allowed: true
        checkPostDataLength: false
        postDataLength: 4096
        checkRequestLength: false
        requestLength: 8192
        checkUrlLength: true
        urlLength: 2048
        checkQueryStringLength: true
        queryStringLength: 2048
        responseCheck: false
      - name: bat
        allowed: false
      - name: pdf
        allowed: false