apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  annotations:
    nginx.org/rewrites: "serviceName=httpbin-svc rewrite=/"
    nginx.org/location-snippets: |
            proxy_set_header X-Script-Name /httpbin;
    #appprotect.f5.com/app-protect-policy: "default/waf-base-httpbin"
    #appprotect.f5.com/app-protect-enable: "True"
    #appprotect.f5.com/app-protect-security-log-enable: "True"
    #appprotect.f5.com/app-protect-security-log: "default/logconf"
    #appprotect.f5.com/app-protect-security-log-destination: "syslog:server=syslog-svc.default:514"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - httpbin-ic.zitechlab.my.id
      secretName: wlc-server-secret
      
  rules:
  - host: httpbin-ic.zitechlab.my.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin-svc
            port:
              number: 80
