apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-ssl-issuer
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: <your@mail-address>

    # config your server here
    # Staging
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Production
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: example-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: <your@mail-address>
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key