apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cafe-letsencript-secret
  namespace: default
spec:
  secretName: cafe-letsencript-secret
  issuerRef:
    name: acme-ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - cafe.zitechlab.my.id